### ISSUE TITLE
Monitoring: Application Dashboard

### ISSUE THREAD

**Issue by panazzo** [cloud104/tks-onboard#12]

**Comment by pagottoo** [comment]
https://grafana.cfcfc2.k8s.us-east-2.aws.tks.sh/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace?orgId=1&var-datasource=prometheus&var-namespace=tks-onboard

**Comment by pagottoo** [comment]
https://grafana.cfcfc2.k8s.us-east-2.aws.tks.sh/d/mY9p7dQmz/kong?orgId=1

**Comment by pagottoo** [comment]
https://grafana.cfcfc2.k8s.us-east-2.aws.tks.sh/d/u_DVKhQiz/tks-onboard-flask-transaction?orgId=1
